// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwcj0mPdu_0gDxv-IzzF6ulX6GZfRilXk',
    appId: '1:382376958676:web:3108a5e48d60ce53083941',
    messagingSenderId: '382376958676',
    projectId: 'projeto-paf',
    authDomain: 'projeto-paf.firebaseapp.com',
    storageBucket: 'projeto-paf.firebasestorage.app',
    measurementId: 'G-C0BEF22X7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComUxbwRumJpj0IOeHDFS_1abIqNM3PM8',
    appId: '1:382376958676:android:8f7ec8e267cf274b083941',
    messagingSenderId: '382376958676',
    projectId: 'projeto-paf',
    storageBucket: 'projeto-paf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qxtSiQtghU6V5OWuBgdwbK7uvcvaQ9g',
    appId: '1:382376958676:ios:c322b63a1252cdab083941',
    messagingSenderId: '382376958676',
    projectId: 'projeto-paf',
    storageBucket: 'projeto-paf.firebasestorage.app',
    androidClientId: '382376958676-4k5qfjjrhfnqko728fplsc04ct3amuc9.apps.googleusercontent.com',
    iosClientId: '382376958676-k6dit5nqapv8rpf271jbkgarn6slic9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qxtSiQtghU6V5OWuBgdwbK7uvcvaQ9g',
    appId: '1:382376958676:ios:c322b63a1252cdab083941',
    messagingSenderId: '382376958676',
    projectId: 'projeto-paf',
    storageBucket: 'projeto-paf.firebasestorage.app',
    androidClientId: '382376958676-4k5qfjjrhfnqko728fplsc04ct3amuc9.apps.googleusercontent.com',
    iosClientId: '382376958676-k6dit5nqapv8rpf271jbkgarn6slic9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwcj0mPdu_0gDxv-IzzF6ulX6GZfRilXk',
    appId: '1:382376958676:web:8b77c107b0496c67083941',
    messagingSenderId: '382376958676',
    projectId: 'projeto-paf',
    authDomain: 'projeto-paf.firebaseapp.com',
    storageBucket: 'projeto-paf.firebasestorage.app',
    measurementId: 'G-D0THRZ0NM9',
  );

}